# Generated by Django 3.2.4 on 2021-07-12 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Framework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=56)),
            ],
            options={
                'verbose_name_plural': 'Frameworks',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=56, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Languages',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick', models.CharField(max_length=56)),
                ('name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('about', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'People',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=56)),
                ('url', models.CharField(blank=True, max_length=256)),
                ('desc', models.TextField(blank=True, null=True)),
                ('frameworks', models.ManyToManyField(blank=True, to='app.Framework')),
                ('languages', models.ManyToManyField(blank=True, to='app.Language')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.person')),
            ],
            options={
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=56, unique=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.person')),
                ('projects', models.ManyToManyField(blank=True, to='app.Project')),
            ],
            options={
                'verbose_name_plural': 'Technologies',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='technologies',
            field=models.ManyToManyField(blank=True, to='app.Technology'),
        ),
        migrations.AddField(
            model_name='language',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.person'),
        ),
        migrations.AddField(
            model_name='language',
            name='projects',
            field=models.ManyToManyField(blank=True, to='app.Project'),
        ),
        migrations.AddField(
            model_name='framework',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.language'),
        ),
        migrations.AddField(
            model_name='framework',
            name='projects',
            field=models.ManyToManyField(blank=True, to='app.Project'),
        ),
    ]
