# Generated by Django 3.2.4 on 2021-07-13 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_person_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='title',
            field=models.CharField(default='Software Engineer', max_length=56),
        ),
    ]
