# Generated by Django 3.2.4 on 2021-07-13 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_person_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='open_source',
            field=models.BooleanField(default=True),
        ),
    ]
